version: '3'
services: 
    db:
        image: 'postgres:latest'
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: events_commerce
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5433:5432"
    app:
        container_name: events-commerce-api
        restart: always
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - db